/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

*/

DECLARE
	@Max INT = 4000000;

WITH [Fibonacci]( F1, F2 ) AS
(
	SELECT
		CAST( 0 AS BIGINT ) AS [F1],
		CAST( 1 AS BIGINT ) AS [F2]
		
	UNION ALL
	
	SELECT
		F2 AS [F1],
		F1 + F2 AS [F2]
	FROM
		[Fibonacci]
	WHERE
		( [F1] + [F2] ) < @Max
)
SELECT
	SUM( F2 ) AS [Result]
FROM
	[Fibonacci] F
WHERE
	[F2] % 2 = 0
OPTION
(
	MAXRECURSION 0
);

GO